# slim is a lightweight image (debian)
FROM python:3.10-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Create a directory for the app
WORKDIR /app

# Install dependencies
COPY  . /app 

RUN apt-get update && apt-get install -y \
    --no-install-recommends gcc \
    && apt-get clean
